package edu.utap.photolist.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class BrewReview(
    // Auth information
    var Title: String = "",
    var ReviewStars: Float = 0F,
    var Notes: String = "",
    var DateTime: String = "",

    //Add other variables here such as ownerID, total time and image ref

    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
