package edu.utap.photolist.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class BrewTemplate(
    // Auth information
    var title: String = "",
    var imageID: String = "",
    var totalTime: String = "",
    var steps: List<BrewStep>? = listOf(),

    //Add other variables here such as ownerID, total time and image ref

    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
